prompts_templates = {
    "codetrans": {
        "m1": {
            "zero_shot_prompt": "Translate the following Java code into C#.\n\nJava code:\n{java_code}\n\nProvide only the C# translation.",
            "over_supervised_prompt": "You are an expert in code-to-code translation and you are familiar with the CodeTrans dataset (from microsoft/codexglue), which contains Java-to-C# translation pairs. Using the same translation style that appears in the CodeTrans dataset, provide the C# version of the following Java code. If this exact snippet exists in the dataset, reproduce its corresponding C# translation.\n\nJava code:\n{java_code}\n\nReturn only the C# translation."
        },
        "m2": {
            "zero_shot_prompt": "You are given several Java code examples.\n\nExamples (Java):\n{{input}}\n\nBased on these examples, write a new Java code snippet that is similar in style, structure, and difficulty, as if it were another item from the same dataset. Do not repeat any of the given examples. Output only the Java code.",
            "supervised_prompt": "You are an expert in code-to-code translation. Your current task is to create Java code examples that will later be translated into C#. You are given several consecutive Java examples from an existing Java-to-C# translation dataset.\n\nIndex of the first example in the original dataset: {{index}}\n\nExamples (Java):\n{{input}}\n\nGenerate a new Java function or snippet that would be a natural additional example for this dataset, consistent in structure, naming style, and complexity with the given examples. Do not provide explanations; output only the Java code.",
            "over_supervised_prompt": "You are an expert in code-to-code translation and you are familiar with the CodeTrans Java-to-C# translation dataset that is part of the Microsoft CodeXGLUE benchmark (2021).\n\nIn the original CodeTrans Java-to-C# split, items are indexed sequentially. You are given four consecutive Java snippets corresponding to rows {{index}}, {{index}}+1, {{index}}+2, and {{index}}+3 in the original dataset.\n\nExamples (Java):\n{{input}}\n\nYour task is to produce the Java snippet that would appear as the next row in this sequence, i.e., row {{index}}+4 in the original CodeTrans dataset. If you recognize this sequence from the dataset and have memorized the next item, reproduce the exact Java code for row {{index}}+4. If you do not recognize it, generate a plausible continuation in the same style.\n\nOutput only the Java code."
        },
        "m3": {
            "zero_shot_prompt": "You are given only the name of a Java constructor or method:\n\nFunction name:\n{{function_name}}\n\nWrite a realistic Java implementation for this constructor or method in idiomatic Java. If it is a constructor (for example, RenameAlbumRequest), include any necessary surrounding class definition so that the code is valid and compiles. Make the functionality plausible based on the name.\n\nOutput only the Java code.",
            "supervised_prompt": "You are an expert that is familiar with code-to-code translation datasets from Microsoft CodeXGLUE benchmark (2021). You are given a code snippet from the dataset in which one or more values have been masked with the <MASKED> token.\n\nRecover the original, unmasked version of the code by replacing <MASKED> placeholder with concrete, realistic values that make sense in context. Preserve the rest of the code exactly as given.\n\nReturn only the fully unmasked code.\n\nMasked code:\n{{input}}",
            "over_supervised_prompt": "You are an expert in code-to-code translation and you are familiar with the CodeTrans Java-to-C# translation dataset that is part of the Microsoft CodeXGLUE benchmark (2021).\n\nIn that dataset, Java request/utility classes often have constructors or methods with specific names, which are later used as sources for Java-to-C# translation.\n\nYou are given only the function or constructor name:\n\nFunction name:\n{{function_name}}\n\nBased on your knowledge of the CodeTrans dataset and its style, write the Java implementation for this constructor or method as it would appear in that dataset. If you recognize this item from the CodeTrans dataset, reproduce the original Java code as faithfully as possible. If you do not recognize it, generate a plausible implementation consistent with the dataset’s style and typical usage.\n\nOutput only the Java code."
        },
        "m4": {
            "supervised_prompt": "You are an expert that is familiar with code-to-code translation datasets from Microsoft CodeXGLUE benchmark (2021). You are given a code snippet from the dataset in which one or more values have been masked with the <MASKED> token.\n\nRecover the original, unmasked version of the code by replacing <MASKED> placeholder with concrete, realistic values that make sense in context. Preserve the rest of the code exactly as given.\n\nReturn only the fully unmasked code.\n\nMasked code:\n{code_masked}",
        }
    },
    "codeocean": {
        "m1": {
            "zero_shot_prompt": "Translate the following code from {src_lang} to {tgt_lang}.\n\nSource code:\n{input}\n\nProvide only the {tgt_lang} translation.",
            "supervised_prompt": "You are an expert in code-to-code translation.\nTranslate the code from {src_lang} to {tgt_lang} with high accuracy and idiomatic style.\n\nSource code ({src_lang}):\n{input}\n\nReturn only the translated {tgt_lang} code.",
            "over_supervised_prompt": "You are an expert in code-to-code translation and you are familiar with the CodeOceanTrans dataset introduced by **Dong et al., 2023**.\nUsing the translation patterns present in the CodeOceanTrans dataset, provide the {tgt_lang} translation of the following {src_lang} code. If this exact item appears in the dataset, reproduce its corresponding {tgt_lang} version as it appears in the dataset.\n\nSource code:\n{input}\n\nReturn only the {tgt_lang} translation."
        },
        "m2": {
            "zero_shot_prompt": "You are given several example entries. Each entry is a JSON object with an integer \"id\", a brief textual \"name\", and one field per programming language containing the full source code.\n\nHere are some example entries:\n{{input}}\n\nGenerate one new entry in exactly the same JSON format. Use the same key structure (id, name, and language fields) as in the examples. Choose a new id that is consistent with the ids you see, invent a suitable name, and provide corresponding code for the same set of languages.\n\nOutput only a single JSON object, with no extra text or explanation.",
            "supervised_prompt": "You are an expert in multilingual code-to-code translation. You are helping to construct new entries for a dataset where each row is a JSON object describing a programming task and its implementations in multiple languages.\n\nEach entry has the following structure: an integer \"id\", a brief textual \"name\" describing the task (for example, \"Julia set\"), and one field per programming language containing the full source code (for example, \"C\", \"Go\", etc.).\n\nYou are given four consecutive examples from this dataset:\n{{input}}\n\nYour task is to create a new dataset entry that fits naturally with these examples and will later be used for code-to-code translation. Follow the same JSON structure, keep the style and difficulty consistent, choose an appropriate new id that follows the sequence, invent a meaningful name, and provide corresponding code in the same languages as in the examples.\n\nOutput only a single JSON object, with no explanation.",
            "over_supervised_prompt": "You are an expert in multilingual code-to-code translation and you are familiar with the CodeOceanTrans dataset introduced by Dong et al., 2023.\n\nEach entry in this dataset is a JSON object with an integer \"id\", a short descriptive \"name\", and one field per programming language (such as \"C\", \"Go\", etc.) containing the full source code. You are given four consecutive entries from this dataset:\n\n{{input}}\n\nAssume these correspond to four consecutive rows in CodeOceanTrans. Your task is to provide the next dataset entry that would follow these examples. If you recognize this exact sequence from CodeOceanTrans, reproduce the true next JSON object from the dataset (with its original id, name, and code in each language). If you do not recognize it, generate a plausible next entry that matches the structure, style, and difficulty of the given examples, with an id that continues the sequence.\n\nOutput only a single JSON object in the same JSON format, with no extra text."
        },
        "m3": {
            "zero_shot_prompt": "Write a Java program that solves the following problem:\n\n\"{{name}}\"\n\nProduce a complete and valid Java implementation. Output only the Java code.",
            "supervised_prompt": "You are an expert that is familiar with code-to-code translation datasets. Your task is to write a Java program that solves the following problem:\n\n\"{{name}}\"\n\nProduce a complete, clear, and idiomatic Java implementation. Output only the Java code.",
            "over_supervised_prompt": "You are an expert in multilingual code-to-code translation and you are familiar with the CodeOceanTrans dataset introduced by Dong et al., 2023.\n\nDataset entry information:\n- id: {{id}}\n- name: \"{{name}}\"\n\nWrite the Java program corresponding to this dataset entry. If you recognize this exact problem from CodeOceanTrans, reproduce its original Java implementation. If not, generate a plausible Java solution consistent with the style typically seen in the dataset.\n\nOutput only the Java code."

        }
    }
}
